import type { Metadata } from "next";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import Header from "./components/overall/Header";
import Navigator from "./components/overall/Navigator";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: { default: "SIMPLAN", template: "Simplan" },
  description: "Generated by SIMPLAN",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={sans.className}>
      {/* TODO: 나중에 border 지우기 */}
      <body className="flex flex-col w-full mx-auto border-2">
        <Header />
        <Navigator />
        {/* grow: 헤더와 네비게이터 사이 공간을 꽉 채우기 위한 코드*/}
        <main className="grow">{children}</main>
      </body>
    </html>
  );
}
