import type { Metadata } from 'next'
import './globals.css';
import { Open_Sans } from 'next/font/google';


const sans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'SIMPLAN',
  description: 'Generated by SIMPLAN',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={sans.className}>
      <body className="flex flex-col w-full max-w-screen-2xl mx-auto border-2">{children}</body>
    </html>
  )
}
